# seed should ideally be in the experiment dictionary, but keeping it at
# the root allows Sacred to manage it.
#seed: 0
collection: null
experiment:
  directories:
    data: "../data"
    logs: "../logs"
  smoke_test: False
  disable_cuda: False
  cuda_device: 0
  default_data_type: "float64"
problem:
  name: "airpass"
  remove_linear_trend: False
  test_size: 0.1
  shuffle: True
model:
  type: "gaussian_process"
  collection: False
  approximation: "exact"
  mean_function:
    type: "constant"
  covariance_function:
    type: "gaussian_spectral_mixture"
    num_mixtures: 5
  likelihood:
    type: "gaussian"
  marginal_log_likelihood:
    type: "exact"
numerics:
  strategy: "maximum_marginal_likelihood"
  load_id: null
  time_budget: null
  infer_while_learning: False
  optimiser:
    type: "sgd"
    learning_rate: 0.05
    num_iterations: 1000
